import { Boardroid } from '../serial/boardroid.js';

const boardroid = new Boardroid();
boardroid.price = 0;
boardroid.price;
boardroid.hasRecycler = true;
boardroid.hasICT = true;
boardroid.hasICT;
await boardroid.coinPurseReadTubes();
await boardroid.banknotePurseAcceptInScrow();
await boardroid.banknotePurseRejectInScrow();
await boardroid.banknotePurseSaveMemory();
await boardroid.banknotePurseReadRecycler();
await boardroid.cardReaderDispense();
await boardroid.paymentPursesDisable();
await boardroid.paymentPursesEnable();
await boardroid.coolingRelayEnable();
await boardroid.coolingRelayDisable();
await boardroid.readTemperature();
await boardroid.testEngines();
await boardroid.hasToReturnChange();
await boardroid.returnChange();
await boardroid.returnInsertedMoney();
