import { PinPad } from '../serial/pinpad.js';

const pinPad = new PinPad();
const key = pinPad.generateKey();
await pinPad.AESEncrypt(key, 'data');
pinPad.asciiToHex('data');
pinPad.base16Decode('hex');
await pinPad.cancelReadCard();
await pinPad.print('1');
pinPad.validateReference('1KJAHBSds4');
await pinPad.validateOperationNumber();
pinPad.processError('a');
await pinPad.getMerchantMOTO();
await pinPad.getMerchant();
await pinPad.getKeyRSA();
pinPad.clear();
await pinPad.readCard();
pinPad.processingEMV();
pinPad.consult();
pinPad.formatAmount(2);
await pinPad.delay(2);
pinPad.verifyVoucher('');
await pinPad.codeError92('', '');
await pinPad.finishEMV('');
pinPad.rePrint();
pinPad.checkInMoto();
pinPad.deleteByName();
pinPad.checkOut();
pinPad.reauthorization();
await pinPad.validateRespCP();
pinPad.username = 'test';
pinPad.password = 'test';
