import { PinPad } from '../serial/pinpad.js';

const pinPad = new PinPad();
const key = pinPad.generateKey();
await pinPad.AESEncrypt(key, 'data');
pinPad.asciiToHex('data');
pinPad.base16Decode('hex');
pinPad.ab2str([]);
await pinPad.cancelReadCard();
await pinPad.print('1');
pinPad.validateReference('1KJAHBSds4');
await pinPad.validateObjectTwo({});
await pinPad.validateOperationNumber();
pinPad.processError('a');
await pinPad.getMerchantMOTO();
await pinPad.getMerchant();
await pinPad.getKeyRSA();
await pinPad.loginUser();
pinPad.clear();
await pinPad.readCard();
await pinPad.writeSerialPinPad('', '');
pinPad.processingEMV();
pinPad.consult();
pinPad.formatAmount(2);
await pinPad.delay(2);
pinPad.verifyVoucher('');
await pinPad.codeError92('','');
await pinPad.finishEMV('');
pinPad.rePrint();
pinPad.checkInMoto();
